version: '3.8'

services:
  app:
    build: .
    env_file:
      - ohapp.env
    ports:
      - "5001:5001"
    volumes:
      - ./:/app
      - sql_volume:/db
      - sql_volume:/logs
      - data_volume:/data
      - temp_volume:/temp

volumes:
  sql_volume:
  data_volume:
  temp_volume: